require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExthousesController do

  # This should return the minimal set of attributes required to create a valid
  # Exthouse. As you add validations to Exthouse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for :exthouse }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExthousesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exthouses as @exthouses" do
      exthouse = Exthouse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exthouses).should eq([exthouse])
    end
  end

  describe "GET show" do
    it "assigns the requested exthouse as @exthouse" do
      exthouse = Exthouse.create! valid_attributes
      get :show, {:id => exthouse.to_param}, valid_session
      assigns(:exthouse).should eq(exthouse)
    end
  end

  describe "GET new" do
    it "assigns a new exthouse as @exthouse" do
      get :new, {}, valid_session
      assigns(:exthouse).should be_a_new(Exthouse)
    end
  end

  describe "GET edit" do
    it "assigns the requested exthouse as @exthouse" do
      exthouse = Exthouse.create! valid_attributes
      get :edit, {:id => exthouse.to_param}, valid_session
      assigns(:exthouse).should eq(exthouse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Exthouse" do
        expect {
          post :create, {:exthouse => valid_attributes}, valid_session
        }.to change(Exthouse, :count).by(1)
      end

      it "assigns a newly created exthouse as @exthouse" do
        post :create, {:exthouse => valid_attributes}, valid_session
        assigns(:exthouse).should be_a(Exthouse)
        assigns(:exthouse).should be_persisted
      end

      it "redirects to the created exthouse" do
        post :create, {:exthouse => valid_attributes}, valid_session
        response.should redirect_to(Exthouse.last)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exthouse" do
        exthouse = Exthouse.create! valid_attributes
        # Assuming there are no other exthouses in the database, this
        # specifies that the Exthouse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Exthouse.any_instance.should_receive(:update_attributes).with({ "serviceorg" => "" })
        put :update, {:id => exthouse.to_param, :exthouse => { "serviceorg" => "" }}, valid_session
      end

      it "assigns the requested exthouse as @exthouse" do
        exthouse = Exthouse.create! valid_attributes
        put :update, {:id => exthouse.to_param, :exthouse => valid_attributes}, valid_session
        assigns(:exthouse).should eq(exthouse)
      end

      it "redirects to the exthouse" do
        exthouse = Exthouse.create! valid_attributes
        put :update, {:id => exthouse.to_param, :exthouse => valid_attributes}, valid_session
        response.should redirect_to(exthouse)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exthouse" do
      exthouse = Exthouse.create! valid_attributes
      expect {
        delete :destroy, {:id => exthouse.to_param}, valid_session
      }.to change(Exthouse, :count).by(-1)
    end

    it "redirects to the exthouses list" do
      exthouse = Exthouse.create! valid_attributes
      delete :destroy, {:id => exthouse.to_param}, valid_session
      response.should redirect_to(exthouses_url)
    end
  end

end
