require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MetrosController do

  # This should return the minimal set of attributes required to create a valid
  # Metro. As you add validations to Metro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MetrosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all metros as @metros" do
      metro = Metro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:metros).should eq([metro])
    end
  end

  describe "GET show" do
    it "assigns the requested metro as @metro" do
      metro = Metro.create! valid_attributes
      get :show, {:id => metro.to_param}, valid_session
      assigns(:metro).should eq(metro)
    end
  end

  describe "GET new" do
    it "assigns a new metro as @metro" do
      get :new, {}, valid_session
      assigns(:metro).should be_a_new(Metro)
    end
  end

  describe "GET edit" do
    it "assigns the requested metro as @metro" do
      metro = Metro.create! valid_attributes
      get :edit, {:id => metro.to_param}, valid_session
      assigns(:metro).should eq(metro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Metro" do
        expect {
          post :create, {:metro => valid_attributes}, valid_session
        }.to change(Metro, :count).by(1)
      end

      it "assigns a newly created metro as @metro" do
        post :create, {:metro => valid_attributes}, valid_session
        assigns(:metro).should be_a(Metro)
        assigns(:metro).should be_persisted
      end

      it "redirects to the created metro" do
        post :create, {:metro => valid_attributes}, valid_session
        response.should redirect_to(Metro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metro as @metro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metro.any_instance.stub(:save).and_return(false)
        post :create, {:metro => { "name" => "invalid value" }}, valid_session
        assigns(:metro).should be_a_new(Metro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Metro.any_instance.stub(:save).and_return(false)
        post :create, {:metro => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metro" do
        metro = Metro.create! valid_attributes
        # Assuming there are no other metros in the database, this
        # specifies that the Metro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Metro.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => metro.to_param, :metro => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested metro as @metro" do
        metro = Metro.create! valid_attributes
        put :update, {:id => metro.to_param, :metro => valid_attributes}, valid_session
        assigns(:metro).should eq(metro)
      end

      it "redirects to the metro" do
        metro = Metro.create! valid_attributes
        put :update, {:id => metro.to_param, :metro => valid_attributes}, valid_session
        response.should redirect_to(metro)
      end
    end

    describe "with invalid params" do
      it "assigns the metro as @metro" do
        metro = Metro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metro.any_instance.stub(:save).and_return(false)
        put :update, {:id => metro.to_param, :metro => { "name" => "invalid value" }}, valid_session
        assigns(:metro).should eq(metro)
      end

      it "re-renders the 'edit' template" do
        metro = Metro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Metro.any_instance.stub(:save).and_return(false)
        put :update, {:id => metro.to_param, :metro => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metro" do
      metro = Metro.create! valid_attributes
      expect {
        delete :destroy, {:id => metro.to_param}, valid_session
      }.to change(Metro, :count).by(-1)
    end

    it "redirects to the metros list" do
      metro = Metro.create! valid_attributes
      delete :destroy, {:id => metro.to_param}, valid_session
      response.should redirect_to(metros_url)
    end
  end

end
