require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OverlapsController do

  # This should return the minimal set of attributes required to create a valid
  # Overlap. As you add validations to Overlap, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OverlapsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all overlaps as @overlaps" do
      overlap = Overlap.create! valid_attributes
      get :index, {}, valid_session
      assigns(:overlaps).should eq([overlap])
    end
  end

  describe "GET show" do
    it "assigns the requested overlap as @overlap" do
      overlap = Overlap.create! valid_attributes
      get :show, {:id => overlap.to_param}, valid_session
      assigns(:overlap).should eq(overlap)
    end
  end

  describe "GET new" do
    it "assigns a new overlap as @overlap" do
      get :new, {}, valid_session
      assigns(:overlap).should be_a_new(Overlap)
    end
  end

  describe "GET edit" do
    it "assigns the requested overlap as @overlap" do
      overlap = Overlap.create! valid_attributes
      get :edit, {:id => overlap.to_param}, valid_session
      assigns(:overlap).should eq(overlap)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Overlap" do
        expect {
          post :create, {:overlap => valid_attributes}, valid_session
        }.to change(Overlap, :count).by(1)
      end

      it "assigns a newly created overlap as @overlap" do
        post :create, {:overlap => valid_attributes}, valid_session
        assigns(:overlap).should be_a(Overlap)
        assigns(:overlap).should be_persisted
      end

      it "redirects to the created overlap" do
        post :create, {:overlap => valid_attributes}, valid_session
        response.should redirect_to(Overlap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved overlap as @overlap" do
        # Trigger the behavior that occurs when invalid params are submitted
        Overlap.any_instance.stub(:save).and_return(false)
        post :create, {:overlap => { "name" => "invalid value" }}, valid_session
        assigns(:overlap).should be_a_new(Overlap)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Overlap.any_instance.stub(:save).and_return(false)
        post :create, {:overlap => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested overlap" do
        overlap = Overlap.create! valid_attributes
        # Assuming there are no other overlaps in the database, this
        # specifies that the Overlap created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Overlap.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => overlap.to_param, :overlap => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested overlap as @overlap" do
        overlap = Overlap.create! valid_attributes
        put :update, {:id => overlap.to_param, :overlap => valid_attributes}, valid_session
        assigns(:overlap).should eq(overlap)
      end

      it "redirects to the overlap" do
        overlap = Overlap.create! valid_attributes
        put :update, {:id => overlap.to_param, :overlap => valid_attributes}, valid_session
        response.should redirect_to(overlap)
      end
    end

    describe "with invalid params" do
      it "assigns the overlap as @overlap" do
        overlap = Overlap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Overlap.any_instance.stub(:save).and_return(false)
        put :update, {:id => overlap.to_param, :overlap => { "name" => "invalid value" }}, valid_session
        assigns(:overlap).should eq(overlap)
      end

      it "re-renders the 'edit' template" do
        overlap = Overlap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Overlap.any_instance.stub(:save).and_return(false)
        put :update, {:id => overlap.to_param, :overlap => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested overlap" do
      overlap = Overlap.create! valid_attributes
      expect {
        delete :destroy, {:id => overlap.to_param}, valid_session
      }.to change(Overlap, :count).by(-1)
    end

    it "redirects to the overlaps list" do
      overlap = Overlap.create! valid_attributes
      delete :destroy, {:id => overlap.to_param}, valid_session
      response.should redirect_to(overlaps_url)
    end
  end

end
