require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceorgsController do

  # This should return the minimal set of attributes required to create a valid
  # Serviceorg. As you add validations to Serviceorg, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServiceorgsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all serviceorgs as @serviceorgs" do
      serviceorg = Serviceorg.create! valid_attributes
      get :index, {}, valid_session
      assigns(:serviceorgs).should eq([serviceorg])
    end
  end

  describe "GET show" do
    it "assigns the requested serviceorg as @serviceorg" do
      serviceorg = Serviceorg.create! valid_attributes
      get :show, {:id => serviceorg.to_param}, valid_session
      assigns(:serviceorg).should eq(serviceorg)
    end
  end

  describe "GET new" do
    it "assigns a new serviceorg as @serviceorg" do
      get :new, {}, valid_session
      assigns(:serviceorg).should be_a_new(Serviceorg)
    end
  end

  describe "GET edit" do
    it "assigns the requested serviceorg as @serviceorg" do
      serviceorg = Serviceorg.create! valid_attributes
      get :edit, {:id => serviceorg.to_param}, valid_session
      assigns(:serviceorg).should eq(serviceorg)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Serviceorg" do
        expect {
          post :create, {:serviceorg => valid_attributes}, valid_session
        }.to change(Serviceorg, :count).by(1)
      end

      it "assigns a newly created serviceorg as @serviceorg" do
        post :create, {:serviceorg => valid_attributes}, valid_session
        assigns(:serviceorg).should be_a(Serviceorg)
        assigns(:serviceorg).should be_persisted
      end

      it "redirects to the created serviceorg" do
        post :create, {:serviceorg => valid_attributes}, valid_session
        response.should redirect_to(Serviceorg.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serviceorg as @serviceorg" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serviceorg.any_instance.stub(:save).and_return(false)
        post :create, {:serviceorg => { "name" => "invalid value" }}, valid_session
        assigns(:serviceorg).should be_a_new(Serviceorg)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serviceorg.any_instance.stub(:save).and_return(false)
        post :create, {:serviceorg => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serviceorg" do
        serviceorg = Serviceorg.create! valid_attributes
        # Assuming there are no other serviceorgs in the database, this
        # specifies that the Serviceorg created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Serviceorg.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => serviceorg.to_param, :serviceorg => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested serviceorg as @serviceorg" do
        serviceorg = Serviceorg.create! valid_attributes
        put :update, {:id => serviceorg.to_param, :serviceorg => valid_attributes}, valid_session
        assigns(:serviceorg).should eq(serviceorg)
      end

      it "redirects to the serviceorg" do
        serviceorg = Serviceorg.create! valid_attributes
        put :update, {:id => serviceorg.to_param, :serviceorg => valid_attributes}, valid_session
        response.should redirect_to(serviceorg)
      end
    end

    describe "with invalid params" do
      it "assigns the serviceorg as @serviceorg" do
        serviceorg = Serviceorg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serviceorg.any_instance.stub(:save).and_return(false)
        put :update, {:id => serviceorg.to_param, :serviceorg => { "name" => "invalid value" }}, valid_session
        assigns(:serviceorg).should eq(serviceorg)
      end

      it "re-renders the 'edit' template" do
        serviceorg = Serviceorg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serviceorg.any_instance.stub(:save).and_return(false)
        put :update, {:id => serviceorg.to_param, :serviceorg => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serviceorg" do
      serviceorg = Serviceorg.create! valid_attributes
      expect {
        delete :destroy, {:id => serviceorg.to_param}, valid_session
      }.to change(Serviceorg, :count).by(-1)
    end

    it "redirects to the serviceorgs list" do
      serviceorg = Serviceorg.create! valid_attributes
      delete :destroy, {:id => serviceorg.to_param}, valid_session
      response.should redirect_to(serviceorgs_url)
    end
  end

end
